fix-install chrony added for images not already containing the service
TOSIT-IO/tdp-collection-prerequisites pull request #94
Opened 2023-11-06 10:12 UTC by jsanc525

#### Which issue(s) this PR fixes

Fixes #93

#### Additional comments

#### Agreements

- [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0).
- [ ] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

2023-11-06 10:35 UTC, rpignolet approved these changes

2023-11-07 14:18 UTC, PACordonnier approved these changes

2023-11-07 14:44 UTC, PACordonnier requested changes
Force push your changes to create an appropriate commit tree

2023-11-07 15:31 UTC, PACordonnier approved these changes

2023-11-07 15:35 UTC, merged